# Generated by Django 4.1.6 on 2023-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_body_topic_created_topic_slug_topic_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
    ]
